### ISSUE TITLE
How to keep the rq worker active when there's job waiting to process

### ISSUE THREAD

**Issue by lzh626** [jezdez/Flask-RQ2#23]
Dear Jezdez, 

I have a flask web app and I am trying to use your flask-rq2 to manage the async queue. 
Due to the nature of async, I've written a separate worker. (I've tried to start the worker inside my web app but without success.). The code the worker is simple.

```
import os
from app import rq, create_app

app = create_app(os.getenv('FLASK_CONFIG') or 'default')
with app.app_context():
    worker = rq.get_worker("high")
    worker.work(burst=True)
```

when I run my web app, I start the worker simply using:  python worker.py. 

It worked to listen to the queue and process the job inside the queue. However, when the jobs are done, it quit automatically. 

Is there a way to keep this worker active all the time. or how it can start automatically when there's job enter the queue?

I'm new to the queue management with rq. any best practice advice to use your package would be very appreciated. 

Thanks a lot,

**Comment by jezdez** [comment]
Oh, sure, just remove the `burst=True` option when calling `worker.work` above. This will basically keep the worker running and wait for new queued jobs. 

It's strongly recommeded to use the [`flask rq worker`](https://flask-rq2.readthedocs.io/en/latest/#commands) command line tool in the upcoming version instead of writing an own worker going forward. Hope this helps.
